/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Up1RouteImport } from './routes/up1'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PresselRouteImport } from './routes/pressel'
import { Route as Obrigado4RouteImport } from './routes/obrigado4'
import { Route as Obrigado3RouteImport } from './routes/obrigado3'
import { Route as Obrigado2RouteImport } from './routes/obrigado2'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItRouteImport } from './routes/it'
import { Route as FrRouteImport } from './routes/fr'
import { Route as EsRouteImport } from './routes/es'
import { Route as EnRouteImport } from './routes/en'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BackRedirectRouteImport } from './routes/back-redirect'
import { Route as AdminCommunityRouteImport } from './routes/admin-community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuleStartHereRouteImport } from './routes/module.start-here'
import { Route as ModulePurchaseInfoRouteImport } from './routes/module.purchase-info'
import { Route as ApiPublicCooudCheckoutRouteImport } from './routes/api/public/cooud/checkout'

const Up1Route = Up1RouteImport.update({
  id: '/up1',
  path: '/up1',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PresselRoute = PresselRouteImport.update({
  id: '/pressel',
  path: '/pressel',
  getParentRoute: () => rootRouteImport,
} as any)
const Obrigado4Route = Obrigado4RouteImport.update({
  id: '/obrigado4',
  path: '/obrigado4',
  getParentRoute: () => rootRouteImport,
} as any)
const Obrigado3Route = Obrigado3RouteImport.update({
  id: '/obrigado3',
  path: '/obrigado3',
  getParentRoute: () => rootRouteImport,
} as any)
const Obrigado2Route = Obrigado2RouteImport.update({
  id: '/obrigado2',
  path: '/obrigado2',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BackRedirectRoute = BackRedirectRouteImport.update({
  id: '/back-redirect',
  path: '/back-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/admin-community',
  path: '/admin-community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleStartHereRoute = ModuleStartHereRouteImport.update({
  id: '/module/start-here',
  path: '/module/start-here',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulePurchaseInfoRoute = ModulePurchaseInfoRouteImport.update({
  id: '/module/purchase-info',
  path: '/module/purchase-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCooudCheckoutRoute = ApiPublicCooudCheckoutRouteImport.update({
  id: '/api/public/cooud/checkout',
  path: '/api/public/cooud/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-community': typeof AdminCommunityRoute
  '/back-redirect': typeof BackRedirectRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/it': typeof ItRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/obrigado3': typeof Obrigado3Route
  '/obrigado4': typeof Obrigado4Route
  '/pressel': typeof PresselRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/up1': typeof Up1Route
  '/module/purchase-info': typeof ModulePurchaseInfoRoute
  '/module/start-here': typeof ModuleStartHereRoute
  '/api/public/cooud/checkout': typeof ApiPublicCooudCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-community': typeof AdminCommunityRoute
  '/back-redirect': typeof BackRedirectRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/it': typeof ItRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/obrigado3': typeof Obrigado3Route
  '/obrigado4': typeof Obrigado4Route
  '/pressel': typeof PresselRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/up1': typeof Up1Route
  '/module/purchase-info': typeof ModulePurchaseInfoRoute
  '/module/start-here': typeof ModuleStartHereRoute
  '/api/public/cooud/checkout': typeof ApiPublicCooudCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-community': typeof AdminCommunityRoute
  '/back-redirect': typeof BackRedirectRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/it': typeof ItRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/obrigado3': typeof Obrigado3Route
  '/obrigado4': typeof Obrigado4Route
  '/pressel': typeof PresselRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/up1': typeof Up1Route
  '/module/purchase-info': typeof ModulePurchaseInfoRoute
  '/module/start-here': typeof ModuleStartHereRoute
  '/api/public/cooud/checkout': typeof ApiPublicCooudCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-community'
    | '/back-redirect'
    | '/checkout'
    | '/community'
    | '/en'
    | '/es'
    | '/fr'
    | '/it'
    | '/login'
    | '/members'
    | '/obrigado'
    | '/obrigado2'
    | '/obrigado3'
    | '/obrigado4'
    | '/pressel'
    | '/profile'
    | '/signup'
    | '/support'
    | '/terms'
    | '/up1'
    | '/module/purchase-info'
    | '/module/start-here'
    | '/api/public/cooud/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-community'
    | '/back-redirect'
    | '/checkout'
    | '/community'
    | '/en'
    | '/es'
    | '/fr'
    | '/it'
    | '/login'
    | '/members'
    | '/obrigado'
    | '/obrigado2'
    | '/obrigado3'
    | '/obrigado4'
    | '/pressel'
    | '/profile'
    | '/signup'
    | '/support'
    | '/terms'
    | '/up1'
    | '/module/purchase-info'
    | '/module/start-here'
    | '/api/public/cooud/checkout'
  id:
    | '__root__'
    | '/'
    | '/admin-community'
    | '/back-redirect'
    | '/checkout'
    | '/community'
    | '/en'
    | '/es'
    | '/fr'
    | '/it'
    | '/login'
    | '/members'
    | '/obrigado'
    | '/obrigado2'
    | '/obrigado3'
    | '/obrigado4'
    | '/pressel'
    | '/profile'
    | '/signup'
    | '/support'
    | '/terms'
    | '/up1'
    | '/module/purchase-info'
    | '/module/start-here'
    | '/api/public/cooud/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  BackRedirectRoute: typeof BackRedirectRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunityRoute: typeof CommunityRoute
  EnRoute: typeof EnRoute
  EsRoute: typeof EsRoute
  FrRoute: typeof FrRoute
  ItRoute: typeof ItRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  ObrigadoRoute: typeof ObrigadoRoute
  Obrigado2Route: typeof Obrigado2Route
  Obrigado3Route: typeof Obrigado3Route
  Obrigado4Route: typeof Obrigado4Route
  PresselRoute: typeof PresselRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  Up1Route: typeof Up1Route
  ModulePurchaseInfoRoute: typeof ModulePurchaseInfoRoute
  ModuleStartHereRoute: typeof ModuleStartHereRoute
  ApiPublicCooudCheckoutRoute: typeof ApiPublicCooudCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/up1': {
      id: '/up1'
      path: '/up1'
      fullPath: '/up1'
      preLoaderRoute: typeof Up1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressel': {
      id: '/pressel'
      path: '/pressel'
      fullPath: '/pressel'
      preLoaderRoute: typeof PresselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado4': {
      id: '/obrigado4'
      path: '/obrigado4'
      fullPath: '/obrigado4'
      preLoaderRoute: typeof Obrigado4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado3': {
      id: '/obrigado3'
      path: '/obrigado3'
      fullPath: '/obrigado3'
      preLoaderRoute: typeof Obrigado3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado2': {
      id: '/obrigado2'
      path: '/obrigado2'
      fullPath: '/obrigado2'
      preLoaderRoute: typeof Obrigado2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-redirect': {
      id: '/back-redirect'
      path: '/back-redirect'
      fullPath: '/back-redirect'
      preLoaderRoute: typeof BackRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-community': {
      id: '/admin-community'
      path: '/admin-community'
      fullPath: '/admin-community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/start-here': {
      id: '/module/start-here'
      path: '/module/start-here'
      fullPath: '/module/start-here'
      preLoaderRoute: typeof ModuleStartHereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/purchase-info': {
      id: '/module/purchase-info'
      path: '/module/purchase-info'
      fullPath: '/module/purchase-info'
      preLoaderRoute: typeof ModulePurchaseInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cooud/checkout': {
      id: '/api/public/cooud/checkout'
      path: '/api/public/cooud/checkout'
      fullPath: '/api/public/cooud/checkout'
      preLoaderRoute: typeof ApiPublicCooudCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  BackRedirectRoute: BackRedirectRoute,
  CheckoutRoute: CheckoutRoute,
  CommunityRoute: CommunityRoute,
  EnRoute: EnRoute,
  EsRoute: EsRoute,
  FrRoute: FrRoute,
  ItRoute: ItRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  ObrigadoRoute: ObrigadoRoute,
  Obrigado2Route: Obrigado2Route,
  Obrigado3Route: Obrigado3Route,
  Obrigado4Route: Obrigado4Route,
  PresselRoute: PresselRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  Up1Route: Up1Route,
  ModulePurchaseInfoRoute: ModulePurchaseInfoRoute,
  ModuleStartHereRoute: ModuleStartHereRoute,
  ApiPublicCooudCheckoutRoute: ApiPublicCooudCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
